appcontact/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import *

urlpatterns = patterns('appcontact.views',
    url(r'^$','index',name='index'),
    url(r'^contacto$','contact_form',name='contact_form'),
    url(r'^inicio$','inicio',name='inicio'),
    url(r'^logout$','logoff',name='logoff'),
    url(r'^mycontacts','mycontacts',name='mycontacts'),
    url(r'^detailcontact/(?P<idc>\d+)/$','detailcontact',name='detailcontact'),
    url(r'^edtcontact/(?P<idc>\d+)/$','edtcontact',name='edtcontact'),
    url(r'^delcontact/(?P<idc>\d+)/$','delcontact',name='delcontact'),
    url(r'^resultados$','resultados',name='resultados'),
    url(r'^edtaccount$','edtaccount',name='edtaccount'),
    url(r'^userreg$','userreg',name='userreg'),

)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += patterns('appcontact.restviews',
    url(r'^login$','login',name='login'),
    url(r'^addcontact$','addcontact',name='addcontact'),
    url(r'^addphoto$','addphoto',name='addphoto'),
    url(r'^delphoto/(?P<idu>\d+)/$','delphoto',name='delphoto'),
    url(r'^location$','restlocation',name='restlocation'),
    url(r'^addtag/$','addtag',name='addtag'),
    url(r'^delnote$','delnote',name='delnote'),
    url(r'^colonia$','colonia',name='colonia'),
    url(r'^addnote$','addnote',name='addnote'),
    url(r'^deltag$','deltag',name='deltag'),
    url(r'^cps$','cps',name='cps'),
    url(r'^edtnote$','edtnote',name='edtnote'),
    url(r'^addreg$','addreg',name='addreg'),
    
)

contactmanager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('appcontact.urls')),
    (r'^', include('appentity.urls')),
    (r'^', include('tasks.urls')),
    url(r'^admin/',include(admin.site.urls)),        
)

tasks/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import *


urlpatterns = patterns('tasks.views',
    #url(r'^calendar','calendar',name='calendar'),
    url(r'^taskform$','taskform',name='taskform'),
    url(r'^addtask$','addtask',name='addtask'),
    url(r'^mytasks$','mytasks',name='mytasks'),
    url(r'^addcat$','addcat',name='addcat'),
    url(r'^deltask$','deltask',name='deltask'),
)

appcontact/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import simplejson
from tasks.models import *


class ContactFiles(models.Model):
    """
    
    Esta Clase contiene las fotos de perfil de los usuarios
    
    """

        #: Doc comment for class attribute Foo.bar.
        #: It can have multiple lines.
    type_file = models.CharField(max_length=200,blank=True)
    contact_file = models.FileField(upload_to='ContactFiles')
    '''
        status params 
         case 0 incomplete
         case 1 Complete
         case 2 Deleted
    '''
class Contact(models.Model):
    """
    
    Esta Clase contiene la información de los contactos.
    Contiene funciones para extraer información relacionada con otros modelos
    
    """
    userrelated = models.ForeignKey(User,null=True,blank=True)
    usercreator = models.IntegerField(null=True,blank=True)
    namec = models.CharField(u'Nombre(s) ',max_length=200)
    lastname = models.CharField(u'Apellido(s)',max_length=200,blank=True,null=True)
    chargec = models.CharField(u'Cargo',max_length=100,blank=True,null=True)
    date_create = models.DateTimeField(default=datetime.now,auto_now_add=True)
    status = models.CharField(max_length=2,default=1)
    estado = models.CharField(u'Estado',max_length=200)
    delomun = models.CharField(u'Del./Municipio',max_length=200)
    colonia = models.CharField(u'Colonia',max_length=200)
    cp = models.CharField(u'C.P.',max_length=10,blank=True,null=True,default=100)
    address = models.CharField(u'Dirección',max_length=200,blank=True,null=True,default=' ')
    lon = models.CharField(max_length=250,default=0)
    lat = models.CharField(max_length=250,default=0)
    extrac = models.TextField(blank=True,null=True)
    photoc = models.IntegerField(blank=True,null=True)
    tags = models.TextField(blank=True,null=True)

    def photoimg(self):
        """
            Esta función retorna el objeto imagen del modelo relación ContactFiles
   
        """
        try: 
            photoim = ContactFiles.objects.get(pk=self.photoc)
        except: 
            photoim = None
        return photoim

    def tages(self):
        """
            Esta función retorna el objeto imagen del modelo relación ContactFiles
   
        """
        if self.tags:
            tags = simplejson.loads(self.tags)
            listing = tags
        else:
            listing = None
        return listing

    def mytasks(self):
        #retorna un objeto con todas las tareas asignadas al contacto seleccionado
        t = Tasking.objects.filter(asigned_string='Contact',asignedto=self.pk)
        return t
    
    def __unicode__(self):
        return u'%s'%self.namec


    """
        las siguiente sfunciones extraen la información de MetaContact para el contacto seleccionado
    """
    def social(self):
        return self.metacontact_set.filter(asignetstring='redsocial')
    # Información de redes sociales

    def contacto(self):
        tels = self.metacontact_set.filter(asignetstring='contact',metastring__icontains='Tel')
        fones = []
        for t in tels:
            metavalue = t.metavalue.replace('|',' ')
            fones.append({'metastring':t.metastring,'metavalue':metavalue})
        return fones
    # Información de contacto...............

    def addresses(self):
        return self.metacontact_set.filter(asignetstring='direccion')
    # Direcciones

class MetaContact(models.Model):
    asignetstring = models.CharField(max_length=200)
    asignetto = models.IntegerField()
    metastring = models.CharField(max_length=200)
    metavalue = models.CharField(max_length=200)
    contact_meta = models.ForeignKey(Contact)




class EmailList(models.Model):
    contacto = models.ForeignKey(Contact)
    email = models.EmailField(unique=True)
    typeofemail = models.CharField(max_length=10,blank=True)


class Tag(models.Model):
    tagname = models.CharField(max_length=200,null=True,default='Untitle')
    def __unicode__(self):
        if self.tagname:
            return '%s' %(self.tagname[0].upper())
    
class Sepomex(models.Model):
    """
        Clase con la información geográfica del país: estados, demelaciones/municipios,Colonias, C.P.
    """
    codigo_postal = models.CharField(max_length=5)
    asentamiento = models.CharField(max_length=250)
    tipo_asentamiento = models.CharField(max_length=100)
    municipio = models.CharField(max_length=250)
    estado = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=250)
    descripcion_codigo_postal = models.CharField(max_length=5)
    clave_estado = models.CharField(max_length=2)
    clave_oficina = models.CharField(max_length=5)
    clave_tipo_asentamiento = models.CharField(max_length=5)
    clave_municipio = models.CharField(max_length=3)
    clave_asentamiento = models.CharField(max_length=2)
    zona = models.CharField(max_length=40)
    clave_ciudad = models.CharField(max_length=2)

class Note(models.Model):
    class Meta:
        ordering = ['date_create']
    
    text = models.TextField(default='untitle')
    sender = models.ForeignKey(User)
    receptor = models.ForeignKey(Contact)
    date_create = models.DateField(auto_now_add=True,default=datetime.now)


TYPES = (('option','option'),
         ('open','text'),
        )
class ExtraFields(models.Model):
    fieldname = models.CharField(u'Nombre del campo',max_length=200)
    typefield = models.CharField(u'Tipo de campo',max_length=200,choices=TYPES)
    ordering = models.IntegerField(default=1)
    
    def __unicode__(self):
        return '%s'%self.fieldname

class OptionFields(models.Model):
    fieldp = models.ForeignKey(ExtraFields)
    optiontxt = models.CharField(u'Opción',max_length=200)

    def __unicode__(self):
        return u'%s'%self.optiontxt

appcontact/templates/forms/eform.html
{% extends extend  %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% block kuppe %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/contacts.css" %}" />
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script type="text/javascript" src="{% static "js/geo.js" %}"></script>
    <script type="text/javascript" src="{% static "js/contacts.js" %}"></script>
    <script type="text/javascript">
        data_colonia = {'estado':$('#id_estado').val()};
        params_to_dropdowns = [{'changer':'#id_estado','victim':'#id_delomun','url':'/location','param':'pk'},
                               {'changer':'#id_delomun','victim':'#id_colonia','url':'/colonia','param':'pk'},
                               {'changer':'#id_colonia','victim':'#id_cp','url':'/cps','param':'pk','data':data_colonia}
                      ];
        var the_place; 
        $(document).ready(function(){
           latt = $('#id_lat').val();
           lonn = $('#id_lon').val();
           if(latt.length>2 && lonn.length>2)
                edition_location(latt,lonn);
           changers(params_to_dropdowns);    
            $( ".combobox").combobox({select:function(){
                $(this).change();    
            }
            
            });
            $('.adder').click(addli);
            $('.deler').click(rmli);
            $('.ajax_send').submit(sendit);
            $('#addphoto').click(submitPhoto);
            $('#contact_file').change(submitPhoto);
            $('#id_colonia').change(localizeme);
            $('.selectable_changer').change(selectable_changer);
            $('.selectable_changer').change();
        });
    </script>
{% endblock %}
{% block content %}
{% load tager%}
<div class="form_box">
    <h2 class="title-1"> Contacto</h2>
    <form name="addcontact" id="addcontact"  method="post" action="/addcontact" enctype="multipart/form-data"  class="ajax_send">
           {%csrf_token%}
           <input type="hidden" name="id" id="id"  value="{{idc}}" />
           <input type="file" name="contact_file" id="contact_file" value=""  style="display:none;" /> 
           {% if idc %}
                {{forma.userrelated}}
                {{forma.usercreator}}
            {% endif %}
           <div class="col-md-9 left_form">
               <ul class="field-list">
                    <li>
                        <label class="inline_blocke" for="id_namec"> {{forma.namec.label}} </label>
                        {{forma.namec|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                    <li>
                        <label class="inline_blocke" for="id_lastname"> {{forma.lastname.label}} </label>
                        {{forma.lastname|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                   <li>
                        <label class="inline_blocke" for="id_chargec"> {{forma.chargec.label}} </label>
                        {{forma.chargec|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                    <li class="blind">
                         <label class="inline_blocke" for="id_organizacion"> Organización </label>
                    </li>

                </ul>
           </div>
           <div class="col-md-3" style="padding:9px 0px;">
                <a href="#/addphoto" id="addphoto" class="btn btn-success" style="width:100%;">Seleccionar imagen</a>
                <div class="rounding">
                    {% if photo%}
                        <img src="/static/{{photo}}" class="myphoto" />
                    {% else %}
                        <img src="/static/images/nophoto.png" class="myphoto"/>
                    {% endif %}
                </div>
           </div>
            <ul>
               {% for cfor in cform %}
               <li class="contact_li">
                   <div class="col-md-9 left_form">
                                <label class="inline_blocke">Contacto</label>
                                {{cfor.typeof|addcss:"form-control inline_blocke field-short selectable_changer"}}
                                {{cfor.contactinfo|addcss:"form-control inline_blocke field-short"}}
                                {{cfor.ext|addcss:"form-control inline_blocke minifield blind"}}
                   </div>
                   <div class="col-md-3 rboxy field-list">
                                {{cfor.whereis|addcss:"form-control inline_blocke field-right-d"}}
                                {% include 'pices/botones.html'%}
                   </div>
               </li>
               {% endfor %}          

               
               {% for cfor in emailform %}
               <li class="contact_li">
                   <div class="col-md-9 left_form">
                                <label class="inline_blocke">Contacto</label>
                                {{cfor.typeof|addcss:"form-control inline_blocke field-short selectable_changer"}}
                                {{cfor.contactinfo|addcss:"form-control inline_blocke field-short"}}
                                {{cfor.ext|addcss:"form-control inline_blocke minifield blind"}}
                   </div>
                   
                   <div class="col-md-3 rboxy field-list">
                                {{cfor.whereis|addcss:"form-control inline_blocke field-right-d minifield"}}
                                {% include 'pices/botones.html'%}
                   </div>
               </li>
               {% endfor %}          
                



            </ul>
            <ul>            
            {% for rsfor in rsform %}
               <li>
               <div class="col-md-9 left_form">
                            <label class="inline_blocke">Red Social</label>
                            {{rsfor.redsociallist|addcss:"form-control inline_blocke field-meddium"}}
               </div>
               
               <div class="col-md-3 rboxy field-list">
                            {{rsfor.redsocial|addcss:"form-control inline_blocke field-right-d"}}
                            {% include 'pices/botones.html'%}
              </div>
               </li>
            {% endfor %}          
               </ul>
               <ul>
               {% for addfor in addsform %}
               <li>
               <div class="col-md-9 left_form">
                            <label class="inline_blocke">Dirección</label>
                            {{addfor.direccion|addcss:"form-control inline_blocke field-meddium"}}
               </div>
               
               <div class="col-md-3 rboxy field-list">
                            {{addfor.whereisdir|addcss:"form-control inline_blocke field-right-d"}}
                </div>
               </li>
               {% endfor %}
            </ul>
            <div style="clear:both;text-align:left;">
                <label style="width:15.5%;" class="inline_blocke">&nbsp;</label>
                <div class="inline_blocke short">
                    <label for="id_estado"> {{forma.estado.label}} </label>
                    {{forma.estado|addcss:"form-control combobox"}}
                </div>
                <div class="inline_blocke  short">
                    <label for="id_delomun"> {{forma.delomun.label}} </label>
                    {{forma.delomun|addcss:"form-control combobox"}}
                </div>
                <br/>
                <label style="width:15.5%;" class="inline_blocke">&nbsp;</label>
               <div class="inline_blocke short">
                    <label for="id_colonia"> {{forma.colonia.label}} </label>
                    {{forma.colonia|addcss:"form-control combobox"}}
                </div>

               <div class="inline_blocke short">
                    <label for="id_cp"> {{forma.cp.label}} </label>
                    {{forma.cp|addcss:"form-control combobox"}}
                </div>

            </div>
            <div style="text-align:left;margin:12px 0px;">
                <label for="id_extrac" style="width:100%;">Información Extra (biografía,notas,comó conoció la Organización)</label>
                {{forma.extrac|addcss:"form-control small-f"}}
           <!-- 
                <div>
                    ¿Quién puede ver este contacto?
                </div>
                <ul>
                    <li>
                        <input type="radio" name="who" value="t"  class="inline_blocke" />
                        <span class="inline_blocke spacing_r">Todos</span>
                    </li>
                    <li>
                        <input type="radio" name="who" value="me" class="inline_blocke" />
                        <span class="inline_blocke spacing_r">Solo yo</span> 
                    </li>
                    <li>
                        <input type="radio" name="who" value="select" class="inline_blocke" />
                        <span class="inline_nblocke spacing_r">Seleccionar gente...</span>
                    </li>
                </ul>
            -->
            
            </div>
                {{forma.lon}}{{forma.lat}}{{forma.photoc}}


            <ul class="blind">
                <li>
                    <div class="inline_blocke" style="width:80%;">
                        <label>Tags</label>
                        <input type="text" name="tags" class="form-control inline_blocke selector" />
                    </div>

                    <div class="inline_blocke" style="padding-top:5%;">
                        <a href="#add" class="adder glyphicon glyphicon-plus-sign">&nbsp;</a>&nbsp;&nbsp;
                        <a href="#remover" class="deler  glyphicon glyphicon-remove-sign">&nbsp;</a>
                    </div>
                </li>
            </ul>
            <div id="map-canvas" class="blind" style="z-index:1;height:300px;width:100%;"></div>
           {% if extraform %}
                {{extraform|as_bootstrap}}
            <hr/>
            {% endif %}
            
            <div style="text-align:left;margin:10px 0px;">
                <input  id="btn_save" type="submit" value="+Agregar" class="btn btn-success"/>
                 o <a href="/mycontacts">Reestablecer</a>
            </div>
            <br/>
        </form>
</div>
{% endblock %}

appcontact/templates/forms/user_form.html
{% extends extend  %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% block kuppe %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/contacts.css" %}" />
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script type="text/javascript" src="{% static "js/geo.js" %}"></script>
    <script type="text/javascript" src="{% static "js/contacts.js" %}"></script>
    <script type="text/javascript">
        data_colonia = {'estado':$('#id_estado').val()};
        params_to_dropdowns = [{'changer':'#id_estado','victim':'#id_delomun','url':'/location','param':'pk'},
                               {'changer':'#id_delomun','victim':'#id_colonia','url':'/colonia','param':'pk'},
                               {'changer':'#id_colonia','victim':'#id_cp','url':'/cps','param':'pk','data':data_colonia}
                      ];
        var the_place; 
        $(document).ready(function(){
           latt = $('#id_lat').val();
           lonn = $('#id_lon').val();
            
            if(latt.length>2 && lonn.length>2)
                edition_location(latt,lonn);
           
           changers(params_to_dropdowns);    
            $( ".combobox").combobox({select:function(){
                $(this).change();    
            }
            
            });
            $('.adder').click(addli);
            $('.deler').click(rmli);
            $('.ajax_send').submit(sendit);
            $('#addphoto').click(submitPhoto);
            $('#contact_file').change(submitPhoto);
            $('#id_colonia').change(localizeme);
            $('.selectable_changer').change(selectable_changer);
            $('.selectable_changer').change();
        });
    </script>
{% endblock %}
{% block content %}
{% load tager%}
<div class="form_box">
    <h2 class="title-1">Registro de usuario</h2>
    <form name="addreg" id="addcontact"  method="post" action="/addreg" enctype="multipart/form-data"  class="ajax_send">
           {%csrf_token%}
           <input type="hidden" name="id" id="id"  value="{{idc}}" />
           <input type="file" name="contact_file" id="contact_file" value=""  style="display:none;" /> 
            <section style="text-align:left;">
            <h2>Login Info</h2>
            <div>
                <label class="inline_blocke" for="username">Nombre de Usuario</label>
                <input id="id_username" type="text" name="username" class="form-control" value="{{user}}"/>
            </div>
            <div>
                <label class="inline_blocke" for="pass">Contraseña</label>
                <input id="id_password" type="password" name="password" class="form-control" />
            </div>
            <div>
                <label class="inline_blocke" for="reppass">Repita Contrsaeña </label>
                <input id="reppass" type="password" name="pass" class="form-control" />
            </div>
            </section>
            
            <h2>Datos Personales</h2>

           {% if idc %}
                {{forma.userrelated}}
                {{forma.usercreator}}
            {% endif %}
           <div class="col-md-9 left_form">
               <ul class="field-list">
                    <li>
                        <label class="inline_blocke" for="id_namec"> {{forma.namec.label}} </label>
                        {{forma.namec|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                    <li>
                        <label class="inline_blocke" for="id_lastname"> {{forma.lastname.label}} </label>
                        {{forma.lastname|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                   <li>
                        <label class="inline_blocke" for="id_chargec"> {{forma.chargec.label}} </label>
                        {{forma.chargec|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                </ul>
           </div>
           <div class="col-md-3" style="padding:9px 0px;">
                <a href="#/addphoto" id="addphoto" class="btn btn-success" style="width:100%;">Seleccionar imagen</a>
                <div class="rounding">
                    {% if photo%}
                        <img src="/static/{{photo}}" class="myphoto" />
                    {% else %}
                        <img src="/static/images/nophoto.png" class="myphoto"/>
                    {% endif %}
                </div>
           </div>
            <ul>
               {% for cfor in cform %}
               <li>
                   <div class="col-md-9 left_form">
                                <label class="inline_blocke">Contacto</label>
                                {{cfor.typeof|addcss:"form-control inline_blocke field-short selectable_changer"}}
                                {{cfor.contactinfo|addcss:"form-control inline_blocke field-short"}}
                                {{cfor.ext|addcss:"form-control inline_blocke minifield blind"}}

                   </div>
                   <div class="col-md-3 rboxy field-list">
                                {{cfor.whereis|addcss:"form-control inline_blocke field-right-d"}}
                                {% include 'pices/botones.html'%}
                   </div>
               </li>
               {% endfor %}          

               
               {% for cfor in emailform %}
               <li>
                   <div class="col-md-9 left_form">
                                <label class="inline_blocke">Contacto</label>
                                {{cfor.typeof|addcss:"form-control inline_blocke field-short selectable_changer"}}
                                {{cfor.contactinfo|addcss:"form-control inline_blocke field-short"}}
                                {{cfor.ext|addcss:"form-control inline_blocke minifield blind"}}

                   </div>
                   
                   <div class="col-md-3 rboxy field-list">
                                {{cfor.whereis|addcss:"form-control inline_blocke field-right-d"}}
                                {% include 'pices/botones.html'%}
                   </div>
               </li>
               {% endfor %}          
                



            </ul>
            <ul>            
            {% for rsfor in rsform %}
               <li>
               <div class="col-md-9 left_form">
                            <label class="inline_blocke">Red Social</label>
                            {{rsfor.redsociallist|addcss:"form-control inline_blocke field-meddium"}}
               </div>
               
               <div class="col-md-3 rboxy field-list">
                            {{rsfor.redsocial|addcss:"form-control inline_blocke field-right-d"}}
                            {% include 'pices/botones.html'%}
              </div>
               </li>
            {% endfor %}          
               </ul>
               <ul>
               {% for addfor in addsform %}
               <li>
               <div class="col-md-9 left_form">
                            <label class="inline_blocke">Dirección</label>
                            {{addfor.direccion|addcss:"form-control inline_blocke field-meddium"}}
               </div>
               
               <div class="col-md-3 rboxy field-list">
                            {{addfor.whereisdir|addcss:"form-control inline_blocke field-right-d"}}
                            {% include 'pices/botones.html'%}
                </div>
               </li>
               {% endfor %}
            </ul>
            <div style="clear:both;text-align:left;">
                <label style="width:15.5%;" class="inline_blocke">&nbsp;</label>
                <div class="inline_blocke short">
                    <label for="id_estado"> {{forma.estado.label}} </label>
                    {{forma.estado|addcss:"form-control combobox"}}
                </div>
                <div class="inline_blocke  short">
                    <label for="id_delomun"> {{forma.delomun.label}} </label>
                    {{forma.delomun|addcss:"form-control combobox"}}
                </div>
                <br/>
                <label style="width:15.5%;" class="inline_blocke">&nbsp;</label>
               <div class="inline_blocke short">
                    <label for="id_colonia"> {{forma.colonia.label}} </label>
                    {{forma.colonia|addcss:"form-control combobox"}}
                </div>

               <div class="inline_blocke short">
                    <label for="id_cp"> {{forma.cp.label}} </label>
                    {{forma.cp|addcss:"form-control combobox"}}
                </div>

            </div>
            <div style="text-align:left;margin:12px 0px;">
                <label for="id_extrac" style="width:100%;">Información Extra (biografía,notas,comó conoció la Organización)</label>
                {{forma.extrac|addcss:"form-control small-f"}}
           <!-- 
                <div>
                    ¿Quién puede ver este contacto?
                </div>
                <ul>
                    <li>
                        <input type="radio" name="who" value="t"  class="inline_blocke" />
                        <span class="inline_blocke spacing_r">Todos</span>
                    </li>
                    <li>
                        <input type="radio" name="who" value="me" class="inline_blocke" />
                        <span class="inline_blocke spacing_r">Solo yo</span> 
                    </li>
                    <li>
                        <input type="radio" name="who" value="select" class="inline_blocke" />
                        <span class="inline_nblocke spacing_r">Seleccionar gente...</span>
                    </li>
                </ul>
            -->
            
            </div>
                {{forma.lon}}{{forma.lat}}{{forma.photoc}}


            <ul class="blind">
                <li>
                    <div class="inline_blocke" style="width:80%;">
                        <label>Tags</label>
                        <input type="text" name="tags" class="form-control inline_blocke selector" />
                    </div>

                    <div class="inline_blocke" style="padding-top:5%;">
                        <a href="#add" class="adder glyphicon glyphicon-plus-sign">&nbsp;</a>&nbsp;&nbsp;
                        <a href="#remover" class="deler  glyphicon glyphicon-remove-sign">&nbsp;</a>
                    </div>
                </li>
            </ul>
            <div id="map-canvas" class="blind" style="z-index:1;height:300px;width:100%;"></div>
           {% if extraform %}
                {{extraform|as_bootstrap}}
            <hr/>
            {% endif %}
            
            <div style="text-align:left;margin:10px 0px;">
                <input  id="btn_save" type="submit" value="+Agregar" class="btn btn-success"/>
                 o <a href="/mycontacts">Reestablecer</a>
            </div>
            <br/>
        </form>
</div>
{% endblock %}