contactmanager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('appcontact.urls')),
    (r'^', include('appentity.urls')),
    (r'^', include('tasks.urls')),
    url(r'^admin/',include(admin.site.urls)),        
)

tasks/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import *


urlpatterns = patterns('tasks.views',
    #url(r'^calendar','calendar',name='calendar'),
    url(r'^taskform$','taskform',name='taskform'),
    url(r'^addtask$','addtask',name='addtask'),
    url(r'^mytasks$','mytasks',name='mytasks'),
    url(r'^addcat$','addcat',name='addcat'),
    url(r'^deltask$','deltask',name='deltask'),
)

tasks/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import simplejson


CHOICES_TASK = (('0','el día del evento'),
                ('1','1 día antes'),
                ('2','2 dias antes'),
)


class Category(models.Model):
    colorful = models.CharField(u'color',max_length=12,default='#04A598')
    categoryname = models.CharField(u'Categoría',max_length=250)
    def __unicode__(self):
        return u'%s'%self.categoryname


class Tasking(models.Model):
    title_task = models.CharField(u'Título',max_length=200)
    when = models.DateField(u'¿Cuándo agregar tarea?')
    categoria = models.ForeignKey(Category,help_text='Agregar Categoría',verbose_name="Seleccione una categoría")
    anytime = models.TimeField(u'¿Horario?',blank=True,null=True)
    asigned_string = models.CharField(max_length=100)
    asignedto = models.IntegerField(blank=True,null=True)
    date_create = models.DateTimeField(auto_now=True)
    reminder = models.CharField(max_length=100,choices=CHOICES_TASK)
    mail_to_send = models.CharField(max_length=200,blank=True,null=True)
    note = models.TextField(blank=True,null=True)
    taskstatus = models.BooleanField(default=0)
    creatore = models.ForeignKey(User)


class Watcher(models.Model):
    taskid = models.ForeignKey(Tasking)
    wathcer = models.TextField()

tasks/views.py
# -*- encoding: utf-8 -*-
from django.http import HttpResponse
from django.template.context import RequestContext
from django.shortcuts import get_object_or_404, render_to_response,render
import simplejson
from appentity.models import * 
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import redirect
from django.contrib.auth import logout
import string as STrg
from appcontact.views import abc_tag_list 
from django.db.models import Q
from calendar import HTMLCalendar
from datetime import date
import datetime as dtf
from tasks.models import *
from contactmanager.forms import *


class WorkCalendar(HTMLCalendar):
    def __init__(self,tasks):
        super(WorkCalendar,self).__init__()
    def formatday(self, day, weekday):
        if day != 0:
            cssclass = self.cssclasses[weekday]
            if date.today() == date(self.year, self.month, day):
                cssclass += ' today' 
            return self.day_cell(cssclass, day)
        return self.day_cell('noday', '&nbsp;')

    def formatmonth(self, year, month):
        self.year, self.month = year, month
        return super(WorkCalendar, self).formatmonth(year, month)

    def group_by_day(self, workouts):
        field = lambda workout: workout.performed_at.day
        return dict(
            [(day, list(items)) for day, items in groupby(workouts, field)]
        )

    def day_cell(self, cssclass, body):
        thap = '#%s/%s/%s' %(self.month,body,self.year)
        return '<td class="%s"><a href="%s" class="addingdate inline_blocke">%s</a></td>' % (cssclass,thap, body)



@login_required(login_url='/')
def taskform(request):
    context = RequestContext(request)
    idedition = request.GET.get('pk',None)
    try: instanced = Tasking.objects.get(pk=idedition)
    except: instanced = None
    args = {}
    forma = FormCreator()
    modelo = Tasking
    asigned = request.GET.get('asignedto',request.user.pk)
    asignedstr = request.GET.get('asgstr','blankTask')
    widgets = {
                'asigned_string':forms.HiddenInput(),
                'creatore':forms.HiddenInput(),
                'taskstatus':forms.HiddenInput(),
                'mail_to_send':forms.HiddenInput(),
                'asignedto':forms.HiddenInput(),
                'anytime':forms.HiddenInput(),
                'note':forms.HiddenInput(),
              }
    initial = {'asigned_string':asignedstr,
               'creatore':request.user,
               'asignedto':asigned,
               'reminder':0,
                } 
    forma = forma.advanced_form_to_model(modelo=modelo,widgets=widgets)
    forma = forma(initial=initial,instance=instanced)
    if request.is_ajax():
            INDEX_EXTEND = 'blank.html'
    else:
        INDEX_EXTEND = 'base2.html'
    
    args['extend']=INDEX_EXTEND
    args['forma']=forma
    args['idtask']=idedition
    return render_to_response('taskform.html',args,context)


@login_required(login_url='/')
def addtask(request):
    context = RequestContext(request)
    response = {}
    ide = request.POST.get('id',None)
    try: 
        instanced = Tasking.objects.get(pk=ide)
    except:
        instanced = None
    forma = FormCreator()
    modelo = Tasking
    data = request.POST.copy()
    forma = forma.form_to_model(modelo)
    forma = forma(data,instance=instanced)
    if forma.is_valid():
        forma.save()
        response['saved']=True
        response['callback']='callbackTask'
    else:
        response = forma.errors
    return HttpResponse(simplejson.dumps(response))
    #if request.is_ajax():
    #    INDEX_EXTEND = 'blank.html'
    #else:
    #    INDEX_EXTEND = 'base2.html'
    
    
    #args['extend']=INDEX_EXTEND
    #args['forma']=forma
    
    #return render_to_response('taskform.html',args,context)

def mytasks(request):
    tasks = Tasking.objects.filter(creatore=request.user.pk)
    args = {}
    args['tasks']=tasks
    return render(request,'mytasks.html',args)


def addcat(request):
    response = {}
    forma = FormCreator()
    modelo = Category
    data = request.POST.copy()
    forma = forma.form_to_model(modelo)
    instanced = Category.objects.filter(categoryname__iexact=data['categoryname'])
    if instanced:
        instanced = instanced[0]
    else:
        instanced = None
    forma = forma(data,instance=instanced)
    if forma.is_valid():
        saved = forma.save()
        response['saved']=saved.pk
    else:
        response = forma.errors
    return HttpResponse(simplejson.dumps(response))


def deltask(request):
    response = {}
    idt = request.GET.get('pk',None)
    if idt:
        t = Tasking.objects.filter(pk=idt)
        t.delete()
        response['doit']='done'
        response['callback']='callbackdeltask'
    else:
        t = None
        response['doit']='no task id'
    return HttpResponse(simplejson.dumps(response))

tasks/templates/calendar.html
{% load tasker %}
<form id="tasking" name="formulario" action="/addtask" method="post">
  {%csrf_token%}
        <input type="hidden" name="asigned_string" value="{{tasks.typeof}}" />
        <input type="hidden" name="asignedto" value="{{tasks.asignedto}}" />
        <div class="btn-group">
            <button type="button" class="btn btn-default calendaring backy">Año Anterior</button>
            <button type="button" class="btn btn-default calendaring backm"> Mes Anterior</button>
            <button type="button" class="btn btn-default calendaring gom"> Mes Siguiente</button>
            <button type="button" class="btn btn-default calendaring goy">Año Sigueinte</button>
        </div>
    <input type="hidden" name="cury" id="cury" value="{{tasks.y}}" />
    <input type="hidden" name="curm" id="curm" value="{{tasks.m}}" />
    <div style="text-align:center;" id="popcalendar">
        {% calendarius tasks.y tasks.m %}
    </div>

    <div id="boxy_float" class="blind">
        <div>
            <label>Evento:</label> 
            <input type="text" name="title_task" value="" class="form-control" placeholder="Nueva Tarea:" maxlength="200"/>
        </div>
        <div>
            <label style="width:100%;">Descripción de la Tarea:</label> 
            <input type="text" name="note" value="" class="form-control" placeholder="Descripción de la Tarea" maxlength="200"/>
        </div>
        <div>
            <label>Cuando:</label>
            <input type="text" class="form-control" id="when"  name="when" value="" readonly />
        </div>
        <div>
            <label>Hora:</label> 
            <div class="input-append bootstrap-timepicker inline_blocke">
                <input id="timepicker1" name="anytime" type="text" class=" form-control">
            </div>
        </div>
        <div class="blind">
        <label>Recordarme:</label>
        <select name="reminder" class="form-control">
            <option value="0">El día del evento</option>
            <option value="1">Un día antes del evento</option>
            <option value="2">Dos dias antes del eventos</option>
        </select>
        </div>
        <div style="margin-top:12px;">
            <input type="submit" value="Guardar" class="btn btn-success" />
            <button type="button" class="closer_task">Cancelar</button>
        </div>
    </div>
</form>

tasks/templates/mytasks.html
{% extends 'base2.html'%}
{% load tager %}
{% load staticfiles %}


{% block kuppe %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/contacts.css" %}" />
    <script type="text/javascript" src="{% static "js/contacts.js" %}"></script>
    <script type="text/javascript" src="{% static "js/chumbukcet.js" %}"></script>
 

    <script type="text/javascript">
    function callbackdeltask(elementore){
        $(elementore).parents('li:first').remove();
    }
    
    function ajaxtasks()
    {
        var wherer = $(this).attr('href');
        var yes = true;
        var elementore = $(this);
        if(wherer.indexOf('deltask')>-1){
            if(confirm('Esta seguro que desea borrar esta tarea?')){
                yess = true; 
            }
            else
                yess = false;

        if(yess)
        {
            $.ajax({url:wherer,type:'get',dataType:'json',success:function(response){
                    if(typeof(window[response.callback])=='function'){
                        window[response.callback](elementore);    
                    }
                }
            });
        }
            
        
        }
        return false;
    }
    

        $(document).ready(function(){
            $('.ajaxcall').click(ajaxtasks);
 
        });
</script>
{% endblock %}


{% block content %}
<div class="table_n">
    
    <div class="table_r white_box">
            <div id="layout_box" class="table_c">
                <h2 class="title-2">Próximas Tareas</h2>
                {% include 'forms/search_form.html'%}
                <!-- Nav tabs -->
                 {% if contacts%}
                    <ul class="pagination">
                        <li>
                            {% if contacts.has_previous %}
                                <a href="?page={{ contacts.previous_page_number }}">Anterior</a>
                            {% endif %}
                        </li>
                        <li>
                             <span class="current">

                                    Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
                            </span>
                        </li>
                        <li>
                             {% if contacts.has_next %}
                                <a href="?page={{ contacts.next_page_number }}">Siguiente</a>
                            {% endif %}

                       </li>
                    </ul>
                {% endif%}
                <div class="tab-content">
                    <ul id="list_result" class="">
                        {% for c in tasks %}
                        <li class="{% cycle 'red' 'even' %}" style="clear:both;">
                            <div class="inline_blocke" style="width:100%;">
                                    <span class="inline_blocke catmodel" style="margin-right:10px;background-color:{{c.categoria.colorful}}">{{c.categoria}}</span>
                                    <span class="t3" style="margin:1% 0%;">{{c.title_task}}</span>
                                </a>
                                <div style="float:right;text-align:right;padding:2px 12px;" class="t5">
                                
                                {{c.when|timesince}}
                                &nbsp;&nbsp;
                                <a href="/taskform?pk={{c.pk}}" data-toggle="modal" data-target="#myModal" class="inline_blocke savecat glyphicon glyphicon-pencil"></a>
                                &nbsp;&nbsp;
                                <a href="/deltask?pk={{c.pk}}" class="ajaxcall inline_blocke glyphicon glyphicon-remove"></a>
                                </div>
                           </div>
                       </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
    </div>
</div>
{% endblock %}

tasks/templates/taskform.html
{% extends extend%}
{% load staticfiles %}
{% load bootstrap_tags %}
{% load tager%}

{% block kuppe %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/contacts.css" %}" />
    <link rel="stylesheet" media="screen" type="text/css" href="/static/css/bootstrap-colorpicker.css" />
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script type="text/javascript" src="{% static "js/geo.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap-colorpicker.js" %}"></script>
    <script type="text/javascript" src="{% static "js/entity.js" %}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
 
            $(function() {
                    $('#id_when').datepicker({dateFormat:"dd/mm/yy",autoSize: true });
                      });
        
            $('.closer').click(function(){
                $('#myModal').modal('hide');    
            });

           $('.cancelarcat').click(function(){
            $('.addcategory').addClass('blind');
            });
            
            $('.addcat').click(function(){
                    $('.addcategory').removeClass('blind');
            });

            $('.ajax_send').submit(sendit);
 
        
             $(function(){
                $('.colores').colorpicker().on('changeColor',function(ev){
                      $(this).css('background-color',ev.color.toHex());
                      $('#colorset').val(ev.color.toHex());
                });;
            });
        
        });


        $('.savecat').click(function(){
            data = {'categoryname':$('[name="newcategoryname"]').val(),
                   'colorful':$('[name="newcolorful"]').val(),
                   'csrfmiddlewaretoken':$('[name="csrfmiddlewaretoken"]').val()
            };

            $.ajax({url:'/addcat',data:data,type:'post',dataType:'json',
                    success:function(response){
                        $('.err').remove();
                        if(response.saved>0)
                        {
                            if($('#id_categoria').find('[value="'+response.saved+'"]').length<1)
                            {
                                $('#id_categoria').append('<option value="'+response.saved+'" selected="selected">'+$('[name="newcategoryname"]').val()+'</option>');
                            }
                            else{
                                    $('#id_categoria').val(response.saved).after('<span class=" err">La categoría ya existe</span>');
                                }
                        }
                        
                    }
            });




        
        });

        

    </script>
 
{% endblock %}


{% block content %}
<div class="form_box task_form">
    <h2 class="title-1">Nueva Tarea</h2>
    <form name="taskform" id="taskform" method="post" action="/addtask" class="ajax_send task_form">
        {%csrf_token%}
        <input type="hidden" name="id" value="{{idtask}}">
        {% if forma %}
            {% for f in forma %}
                {% if not f.is_hidden %}
                    <div class="field_box">
                    <label for="id_{{f.name}}">{{f.label}}</label>
                    {% endif %}
                    {% if f.name in 'categoria' %}
                    {{f|addcss:"form-control inline_blocke"}}
                   {% if f.help_text%}
                        <a href="#addcat" data="{{f.help_text}}" class="addcat inline_blocke">{{f.help_text}}</a>
                        <div class="addcategory blind" style="margin:20px 0px;width:100%;">
                            <div class="inline_blocke"i style="width:80%;">
                            <div class="input-group">
                                <input type="text" class="form-control"  name="newcategoryname" placeholder="Nombre de categoría"/>
                                <input type="hidden" id="colorset" name="newcolorful" class="colores" value="#5367ce" />
                                <span class="input-group-addon">
                                    <i></i>
                                    <div class="colores inline_blocke">&nbsp;</div>
                                </span>
                            </div>
                            </div>
                            <div class="inline_blocke" style="text-align:left;margin:2px 0px;">&nbsp;&nbsp;
                                <button class=" inline_blocke savecat glyphicon glyphicon-ok" type="button"></button>&nbsp;&nbsp;
                                <button type="button" class="inline_blocke glyphicon glyphicon-remove cancelarcat"></button>
                            </div>
                        </div>
                   {% endif %}
                    </div>
                {% else %}
                    {{f|addcss:"form-control"}}
                {% endif%}
            {% endfor %}
        {% endif %}
        <div class="botonera">
            <input type="submit" value="GUARDAR" class="btn btn-success" />
            <button type="button" class="btn closer">Cancelar</button>
        </div>
    </form>

</div> 

{% endblock %}