appentity/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import *
urlpatterns = patterns('appentity.views',
    url(r'^entity','entity',name='entity'),
    url(r'^myentities','myentities',name='myentities'),
    url(r'^entity','entity',name='entity'),
    url(r'^detailentity/(?P<ide>\d+)/$','detailentity',name='detailentity'),
    url(r'^editentity/(?P<ide>\d+)/$','editentity',name='editentity'),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += patterns('appentity.restviews',
    url(r'^addphotoentity$','addphoto',name='addphoto'),
    url(r'^edelphoto/(?P<idu>\d+)/$','delphoto',name='delphoto'),
    url(r'^addentity','addentity',name='addentity'),
    url(r'^relcontacts','relcontacts',name='relcontacts'),
    url(r'^removethis/(?P<idc>\d+)/(?P<ide>\d+)','removerel',name='removerel'), 
 )

contactmanager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('appcontact.urls')),
    (r'^', include('appentity.urls')),
    (r'^', include('tasks.urls')),
    url(r'^admin/',include(admin.site.urls)),        
)

tasks/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import *


urlpatterns = patterns('tasks.views',
    #url(r'^calendar','calendar',name='calendar'),
    url(r'^taskform$','taskform',name='taskform'),
    url(r'^addtask$','addtask',name='addtask'),
    url(r'^mytasks$','mytasks',name='mytasks'),
    url(r'^addcat$','addcat',name='addcat'),
    url(r'^deltask$','deltask',name='deltask'),
)

appcontact/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import simplejson
from tasks.models import *


class ContactFiles(models.Model):
    """
    
    Esta Clase contiene las fotos de perfil de los usuarios
    
    """

        #: Doc comment for class attribute Foo.bar.
        #: It can have multiple lines.
    type_file = models.CharField(max_length=200,blank=True)
    contact_file = models.FileField(upload_to='ContactFiles')
    '''
        status params 
         case 0 incomplete
         case 1 Complete
         case 2 Deleted
    '''
class Contact(models.Model):
    """
    
    Esta Clase contiene la información de los contactos.
    Contiene funciones para extraer información relacionada con otros modelos
    
    """
    userrelated = models.ForeignKey(User,null=True,blank=True)
    usercreator = models.IntegerField(null=True,blank=True)
    namec = models.CharField(u'Nombre(s) ',max_length=200)
    lastname = models.CharField(u'Apellido(s)',max_length=200,blank=True,null=True)
    chargec = models.CharField(u'Cargo',max_length=100,blank=True,null=True)
    date_create = models.DateTimeField(default=datetime.now,auto_now_add=True)
    status = models.CharField(max_length=2,default=1)
    estado = models.CharField(u'Estado',max_length=200)
    delomun = models.CharField(u'Del./Municipio',max_length=200)
    colonia = models.CharField(u'Colonia',max_length=200)
    cp = models.CharField(u'C.P.',max_length=10,blank=True,null=True,default=100)
    address = models.CharField(u'Dirección',max_length=200,blank=True,null=True,default=' ')
    lon = models.CharField(max_length=250,default=0)
    lat = models.CharField(max_length=250,default=0)
    extrac = models.TextField(blank=True,null=True)
    photoc = models.IntegerField(blank=True,null=True)
    tags = models.TextField(blank=True,null=True)

    def photoimg(self):
        """
            Esta función retorna el objeto imagen del modelo relación ContactFiles
   
        """
        try: 
            photoim = ContactFiles.objects.get(pk=self.photoc)
        except: 
            photoim = None
        return photoim

    def tages(self):
        """
            Esta función retorna el objeto imagen del modelo relación ContactFiles
   
        """
        if self.tags:
            tags = simplejson.loads(self.tags)
            listing = tags
        else:
            listing = None
        return listing

    def mytasks(self):
        #retorna un objeto con todas las tareas asignadas al contacto seleccionado
        t = Tasking.objects.filter(asigned_string='Contact',asignedto=self.pk)
        return t
    
    def __unicode__(self):
        return u'%s'%self.namec


    """
        las siguiente sfunciones extraen la información de MetaContact para el contacto seleccionado
    """
    def social(self):
        return self.metacontact_set.filter(asignetstring='redsocial')
    # Información de redes sociales

    def contacto(self):
        tels = self.metacontact_set.filter(asignetstring='contact',metastring__icontains='Tel')
        fones = []
        for t in tels:
            metavalue = t.metavalue.replace('|',' ')
            fones.append({'metastring':t.metastring,'metavalue':metavalue})
        return fones
    # Información de contacto...............

    def addresses(self):
        return self.metacontact_set.filter(asignetstring='direccion')
    # Direcciones

class MetaContact(models.Model):
    asignetstring = models.CharField(max_length=200)
    asignetto = models.IntegerField()
    metastring = models.CharField(max_length=200)
    metavalue = models.CharField(max_length=200)
    contact_meta = models.ForeignKey(Contact)




class EmailList(models.Model):
    contacto = models.ForeignKey(Contact)
    email = models.EmailField(unique=True)
    typeofemail = models.CharField(max_length=10,blank=True)


class Tag(models.Model):
    tagname = models.CharField(max_length=200,null=True,default='Untitle')
    def __unicode__(self):
        if self.tagname:
            return '%s' %(self.tagname[0].upper())
    
class Sepomex(models.Model):
    """
        Clase con la información geográfica del país: estados, demelaciones/municipios,Colonias, C.P.
    """
    codigo_postal = models.CharField(max_length=5)
    asentamiento = models.CharField(max_length=250)
    tipo_asentamiento = models.CharField(max_length=100)
    municipio = models.CharField(max_length=250)
    estado = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=250)
    descripcion_codigo_postal = models.CharField(max_length=5)
    clave_estado = models.CharField(max_length=2)
    clave_oficina = models.CharField(max_length=5)
    clave_tipo_asentamiento = models.CharField(max_length=5)
    clave_municipio = models.CharField(max_length=3)
    clave_asentamiento = models.CharField(max_length=2)
    zona = models.CharField(max_length=40)
    clave_ciudad = models.CharField(max_length=2)

class Note(models.Model):
    class Meta:
        ordering = ['date_create']
    
    text = models.TextField(default='untitle')
    sender = models.ForeignKey(User)
    receptor = models.ForeignKey(Contact)
    date_create = models.DateField(auto_now_add=True,default=datetime.now)


TYPES = (('option','option'),
         ('open','text'),
        )
class ExtraFields(models.Model):
    fieldname = models.CharField(u'Nombre del campo',max_length=200)
    typefield = models.CharField(u'Tipo de campo',max_length=200,choices=TYPES)
    ordering = models.IntegerField(default=1)
    
    def __unicode__(self):
        return '%s'%self.fieldname

class OptionFields(models.Model):
    fieldp = models.ForeignKey(ExtraFields)
    optiontxt = models.CharField(u'Opción',max_length=200)

    def __unicode__(self):
        return u'%s'%self.optiontxt

appentity/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
import simplejson
from appcontact.models import Contact


class EntityFile(models.Model):
    type_file = models.CharField(max_length=200,blank=True)
    entity_file = models.FileField(upload_to='entityFiles')
    '''
        status params 
         case 0 incomplete
         case 1 Complete
         case 2 Deleted
    
    '''

class Entity(models.Model):
    user = models.ForeignKey(User)
    nameac = models.CharField(u'Nombre Org.',max_length=200)
    emailacoount = models.CharField(u'Email',max_length=100,blank=True)
    url = models.CharField(u'Web',max_length=200,blank=True,null=True)
    extra = models.TextField(blank=True,null=True)
    photoa = models.IntegerField(blank=True,null=True)
    date_create = models.DateTimeField(auto_now_add=True)
    cpac = models.CharField(u'C.P.',max_length=20,null=True,blank=True)
    lonac = models.FloatField(default=0,blank=True,null=True)
    latac = models.FloatField(default=0,blank=True,null=True)
    estadoa = models.CharField(u'Estado',max_length=200)
    delomun = models.CharField(u'Del/Municipio',max_length=200)
    colonia = models.CharField(u'Colonia',max_length=200)
    tags = models.TextField(blank=True,null=True)

    def photoimg(self):
        try:
            photoim = EntityFile.objects.get(pk=self.photoa)
        except:
            photoim = None
        return photoim

    def mysocial(self):
        myc = self.metaentity_set.filter(asignetstring='redsocial')
        return myc

    def myaddrs(self):
        myc = self.metaentity_set.filter(asignetstring='direccion')
        return myc

    def tages(self):
        if self.tags:
            l = simplejson.loads(self.tags)
        else:
            l = None
        return l
    def __unicode__(self):
        return u'%s' % self.nameac


class EntitySocialInfo(models.Model):
    entity_id = models.ForeignKey(Entity)
    social_accounts = models.TextField()

class MetaEntity(models.Model):
    asignetstring = models.CharField(max_length=200)
    asignetto = models.IntegerField()
    metastring = models.CharField(max_length=200)
    metavalue = models.CharField(max_length=200)
    contact_meta = models.ForeignKey(Entity)




class As_Contact(models.Model):
    asociation = models.ForeignKey(Entity)
    contacto = models.ForeignKey(Contact)
    date_create = models.DateTimeField(auto_now=True)
 

appentity/templates/forms/entity_form.html
{% extends 'base2.html'%}
{% load staticfiles %}

{% block kuppe %}

    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/forms.css" %}" />
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script type="text/javascript" src="{% static "js/validations.js" %}"></script>
    <script type="text/javascript" src="{% static "js/forms.js" %}"></script>
    <script type="text/javascript" src="{% static "js/geo.js" %}"></script>
    <script type="text/javascript">
        
        {% for em in emails %}
            emails.push('{{em.email}}');
        {% endfor%}
    </script> 

{% endblock %}

{% block content %}
<div class="forms_box">

    <form name="addentity" id="addentity"  method="post" action="addentity" enctype="multipart/form-data">
           {%csrf_token%}
           <input type="hidden" name="id" id="id" />
           <input type="hidden" name="photoa" id="photoa" />
            <div id="generalinfo_box">
                 <div class="hdform">Agregar nueva Organización o <a href="/contacto" class="t5">agregar Contacto</a></div>
               <div id="texts_box" class="inline_blocke">
                    <ul>
                        <li>
                            <label class="inline_blocke" to="nameac">Organización</label>
                            <input type="text" name="nameac" id="nameac" maxlength="100" tabindex="1"  class="void form-control" placeholder=""/>
                        </li>
                        <li>
                          <label to="twitteract" class="inline_blocke">Twitter</label>
                          <input type="text" name="twitteract" id="twitteract" maxlength="100" class="form-control" />
                        </li>
                         <li>
                          <label to="twitteract" class="inline_blocke">Tag</label>
                          <input type="text" name="tag" id="tag" maxlength="100" class="form-control" />
                        </li>
                   </ul>
                </div>
                <div id="photo_box" class="inline_blocke">
                    <div>
                         <span class="inline_blocke imagen_label">Agregar Imágen</span> 
                        <input type="file" name="entity_file" id="entity_file" class="blind"  />
                        <a href="#addphoto" id="addephoto" class="inline_blocke">Seleccionar Archivo</a>
                    </div>
                     <div class="loadphoto"></div>
                     <br/>
                    <div>
                        <a href="#delphoto" class=" delphoto">Eliminar</a>
                        <img src="{% static "images/nophoto.jpg"%}" class="myphoto" height="90px" />
                    </div>
                </div>
            </div>
            <ul id="list_fields">
             {% for a in lista%}
                {% include "pices/ioptioner.html"%} 
             {% endfor %}

                <li>
                    <label class="inline_blocke">Estado</label>
                    <select id="estadoa" name="estadoa" class="location_drop form-control" >
                        <option value="">Seleccione</option>
                        {% for std in estados %}
                            <option value="{{std.estado}}">{{std.estado}}</option>
                        {% endfor %}
                    </select>
                </li>
               <li>
                    <label class="inline_blocke" id="tomunicipio">Del./Municipio</label>
                    <select name="delomun" id="delomun" disabled="disabled" class="form-control">
                    <option value="">Debe seleccionar un Estado</option>
                    </select>
                </li>
               <li>
                    <label class="inline_blocke" id="tocolonia">Colonia</label>
                     <select name="colonia" id="colonia" disabled="disabled" class="form-control">
                    <option value="">Debe seleccionar un Municipio</option>
                    </select>
                </li>
                <li>
                <div id="map-canvas" class="blind" style="z-index:1;height:300px;width:100%;"></div>
                </li>

                <li>
                    <label to="address" class="inline_blocke">Dirección</label>
                    <input type="text" name="addressac"  id="addressac" maxlength="100" class="form-control" />
                </li>
                <li>
                    <label to="cpac" class="inline_blocke">C.P.</label>
                    <input type="text" name="cpac" id="cpac" maxlength="10" style="width:80px;" class="void form-control" />
                    <input type="hidden" name="latac" id="latac" />
                    <input type="hidden" name="lonac" id="lonac" />
                </li>
                <li>
                    <label to="extra" class="inline_blocke">Extra</label><br/>
                    <textarea name="extra" id="extra" rows="3" class="form-control"></textarea>
                </li>
            </ul>
           <div id="btn_green">
                <span class="inline_blocke" id ="saver_box">
                    <a href="/myentities" data-dismiss="modal" class="btn btn-default" >Cancelar</a>
                    <input  id="btn_save" type="submit" value="Guardar" class="btn btn-success"/>
                </span> 
            </div>
       </form>
<br/>

</div>
{% endblock %}

appentity/templates/forms/eyform.html
{% extends extend  %}

{% load staticfiles %}
{% load bootstrap_tags %}

{% block kuppe %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/contacts.css" %}" />
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script type="text/javascript" src="{% static "js/geo.js" %}"></script>
    <script type="text/javascript" src="{% static "js/entity.js" %}"></script>
    <script type="text/javascript">
        data_colonia = {'estado':$('#id_estadoa').val()};
        params_to_dropdowns = [{'changer':'#id_estadoa','victim':'#id_delomun','url':'/location','param':'pk'},
                               {'changer':'#id_delomun','victim':'#id_colonia','url':'/colonia','param':'pk'},
                               {'changer':'#id_colonia','victim':'#id_cpac','url':'/cps','param':'pk','data':data_colonia}];
        var the_place; 
 
        $(document).ready(function(){

           latt = $('#id_latac').val();
           lonn = $('#id_lonac').val();
           if(latt.length>2 && lonn.length>2)
                edition_location(latt,lonn);
 
            changers(params_to_dropdowns);    
            $( ".combobox").combobox({select:function(){
                $(this).change();    
                }
            }); 

           $('.adder').click(addli);
           $('.deler').click(rmli);
           $('.ajax_send').submit(sendit);
           $('#addphoto').click(submitPhoto);
           $('#entity_file').change(submitPhoto);
           $('#id_colonia').change(localizeme);
        });
    </script>
 
{% endblock %}

{% block content %}
{% load tager%}
<div class="form_box">
    <h2 class="title-1"> Editando Organizacion</h2>
    <form name="addentity" id="addentity"  method="post" action="/addentity" enctype="multipart/form-data"  class="ajax_send">
           {%csrf_token%}
           <input type="hidden" name="id" id="id"  value="{{ide}}" />
           <input type="file" name="entity_file" id="entity_file" value=""  style="display:none;" /> 
           <div class="col-md-9 left_form">
                <ul class="field-list">
                    <li>
                        <label class="inline_blocke" for="id_namec"> {{forma.nameac.label}} </label>
                        {{forma.nameac|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                   <li>
                        <label class="inline_blocke" for="id_chargec"> {{forma.emailacoount.label}} </label>
                        {{forma.emailacoount|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                   <li>
                        <label class="inline_blocke" for="id_chargec"> {{forma.url.label}} </label>
                        {{forma.url|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                </ul>
           </div>
           <div class="col-md-3" style="padding:9px 0px;">
                <a href="#/addphoto" id="addphoto" class="btn btn-success" style="width:100%;">Seleccionar imagen</a>
                <div class="rounding">
                    {% if photo%}
                        <img src="/static/{{photo}}" class="myphoto" />
                    {% else %}
                        <img src="/static/images/nophoto.png" class="myphoto"/>
                    {% endif %}
                </div>
           </div>
            <ul>

                        {% for cfor in cformc %}
               <li>
               <div class="col-md-9 left_form">
                            <label class="inline_blocke">Contacto</label>
                            {{cfor.typeof|addcss:"form-control inline_blocke field-short"}}
                            {{cfor.contactinfo|addcss:"form-control inline_blocke field-short"}}
               </div>
               
               <div class="col-md-3 rboxy field-list">
                            {{cfor.whereis|addcss:"form-control inline_blocke field-right-d"}}
                            <a href="#add" class="adder fright inline_blocke glyphicon glyphicon-plus-sign"></a>
                            <a href="#remover" class="deler fright inline_blocke glyphicon glyphicon-remove-sign blind"></a>
               </div>
               </li>

                        {% endfor %}          
            </ul>
            <ul>            
            {% for rsfor in rsform %}
               <li>
               <div class="col-md-9 left_form">
                            <label class="inline_blocke">Red Social</label>
                            {{rsfor.redsociallist|addcss:"form-control inline_blocke field-meddium"}}
               </div>
               
               <div class="col-md-3 rboxy field-list">
                            {{rsfor.redsocial|addcss:"form-control inline_blocke field-right-d"}}
                            {% include 'pices/botones.html'%}
              </div>
               </li>
            {% endfor %}          
               </ul>
               <ul>
               {% for addfor in addsform %}
               <li>
               <div class="col-md-9 left_form">
                            <label class="inline_blocke">Dirección</label>
                            {{addfor.direccion|addcss:"form-control inline_blocke field-meddium"}}
               </div>
               
               <div class="col-md-3 rboxy field-list">
                            {{addfor.whereisdir|addcss:"form-control inline_blocke field-right-d"}}
                            {% include 'pices/botones.html'%}
              </div>
               </li>
               {% endfor %}
            </ul>
            <div style="clear:both;text-align:left;">
                <label style="width:15.5%;" class="inline_blocke">&nbsp;</label>
                <div class="inline_blocke  short">
                    <label for="id_estado"> {{forma.estadoa.label}} </label>
                    {{forma.estadoa|addcss:"form-control combobox"}}
                </div>
                <div class="inline_blocke  short">
                    <label for="id_delomun"> {{forma.delomun.label}} </label>
                    {{forma.delomun|addcss:"form-control combobox"}}
                </div>
                <br/>
                <label style="width:15.5%;" class="inline_blocke">&nbsp;</label>
               <div class="inline_blocke short">
                    <label for="id_colonia"> {{forma.colonia.label}} </label>
                    {{forma.colonia|addcss:"form-control combobox"}}
                </div>

               <div class="inline_blocke short">
                    <label for="id_cp"> {{forma.cpac.label}} </label>
                    {{forma.cpac|addcss:"form-control combobox"}}
                </div>

            </div>
            <div style="text-align:left;margin:12px 0px;">
                <label for="id_extrac" style="width:100%;">Información Extra (biografía,notas,comó conoció la Organización)</label>
                {{forma.extra|addcss:"form-control small-f"}}
            
                <div class="blind">
                    ¿Quién puede ver este contacto?
                </div>
                <ul class="blind">
                    <li>
                        <input type="radio" name="who" value="t"  class="inline_blocke" />
                        <span class="inline_blocke spacing_r">Todos</span>
                    </li>
                    <li>
                        <input type="radio" name="who" value="me" class="inline_blocke" />
                        <span class="inline_blocke spacing_r">Solo yo</span> 
                    </li>
                    <li>
                        <input type="radio" name="who" value="select" class="inline_blocke" />
                        <span class="inline_nblocke spacing_r">Seleccionar gente...</span>
                    </li>
                </ul>
            
            </div>
                {{forma.lonac}}{{forma.latac}}{{forma.photoa}}
            <ul class="blind">
                <li>
                    <div class="inline_blocke" style="width:80%;">
                        <label>Tags</label>
                        <input type="text" name="tags" class="form-control inline_blocke selector" />
                    </div>

                    <div class="inline_blocke" style="padding-top:5%;">
                        <a href="#add" class="adder glyphicon glyphicon-plus-sign">&nbsp;</a>&nbsp;&nbsp;
                        <a href="#remover" class="deler  glyphicon glyphicon-remove-sign">&nbsp;</a>
                    </div>
                </li>
            </ul>
            <div id="map-canvas" class="blind" style="z-index:1;height:300px;width:100%;"></div>
           {% if extraform %}
                {{extraform|as_bootstrap}}
            <hr/>
            {% endif %}
            
            <div style="text-align:left;margin:10px 0px;">
                <input  id="btn_save" type="submit" value="+Agregar" class="btn btn-success"/>
                 o <a href="/mycontacts">Reestablecer</a>
            </div>
            <br/>
        </form>
</div>
{% endblock %}