appcontact/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import *

urlpatterns = patterns('appcontact.views',
    url(r'^$','index',name='index'),
    url(r'^contacto$','contact_form',name='contact_form'),
    url(r'^inicio$','inicio',name='inicio'),
    url(r'^logout$','logoff',name='logoff'),
    url(r'^mycontacts','mycontacts',name='mycontacts'),
    url(r'^detailcontact/(?P<idc>\d+)/$','detailcontact',name='detailcontact'),
    url(r'^edtcontact/(?P<idc>\d+)/$','edtcontact',name='edtcontact'),
    url(r'^delcontact/(?P<idc>\d+)/$','delcontact',name='delcontact'),
    url(r'^resultados$','resultados',name='resultados'),
    url(r'^edtaccount$','edtaccount',name='edtaccount'),
    url(r'^userreg$','userreg',name='userreg'),

)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += patterns('appcontact.restviews',
    url(r'^login$','login',name='login'),
    url(r'^addcontact$','addcontact',name='addcontact'),
    url(r'^addphoto$','addphoto',name='addphoto'),
    url(r'^delphoto/(?P<idu>\d+)/$','delphoto',name='delphoto'),
    url(r'^location$','restlocation',name='restlocation'),
    url(r'^addtag/$','addtag',name='addtag'),
    url(r'^delnote$','delnote',name='delnote'),
    url(r'^colonia$','colonia',name='colonia'),
    url(r'^addnote$','addnote',name='addnote'),
    url(r'^deltag$','deltag',name='deltag'),
    url(r'^cps$','cps',name='cps'),
    url(r'^edtnote$','edtnote',name='edtnote'),
    url(r'^addreg$','addreg',name='addreg'),
    
)

contactmanager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('appcontact.urls')),
    (r'^', include('appentity.urls')),
    (r'^', include('tasks.urls')),
    url(r'^admin/',include(admin.site.urls)),        
)

tasks/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import *


urlpatterns = patterns('tasks.views',
    #url(r'^calendar','calendar',name='calendar'),
    url(r'^taskform$','taskform',name='taskform'),
    url(r'^addtask$','addtask',name='addtask'),
    url(r'^mytasks$','mytasks',name='mytasks'),
    url(r'^addcat$','addcat',name='addcat'),
    url(r'^deltask$','deltask',name='deltask'),
)

appcontact/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import simplejson
from tasks.models import *


class ContactFiles(models.Model):
    """
    
    Esta Clase contiene las fotos de perfil de los usuarios
    
    """

        #: Doc comment for class attribute Foo.bar.
        #: It can have multiple lines.
    type_file = models.CharField(max_length=200,blank=True)
    contact_file = models.FileField(upload_to='ContactFiles')
    '''
        status params 
         case 0 incomplete
         case 1 Complete
         case 2 Deleted
    '''
class Contact(models.Model):
    """
    
    Esta Clase contiene la información de los contactos.
    Contiene funciones para extraer información relacionada con otros modelos
    
    """
    userrelated = models.ForeignKey(User,null=True,blank=True)
    usercreator = models.IntegerField(null=True,blank=True)
    namec = models.CharField(u'Nombre(s) ',max_length=200)
    lastname = models.CharField(u'Apellido(s)',max_length=200,blank=True,null=True)
    chargec = models.CharField(u'Cargo',max_length=100,blank=True,null=True)
    date_create = models.DateTimeField(default=datetime.now,auto_now_add=True)
    status = models.CharField(max_length=2,default=1)
    estado = models.CharField(u'Estado',max_length=200)
    delomun = models.CharField(u'Del./Municipio',max_length=200)
    colonia = models.CharField(u'Colonia',max_length=200)
    cp = models.CharField(u'C.P.',max_length=10,blank=True,null=True,default=100)
    address = models.CharField(u'Dirección',max_length=200,blank=True,null=True,default=' ')
    lon = models.CharField(max_length=250,default=0)
    lat = models.CharField(max_length=250,default=0)
    extrac = models.TextField(blank=True,null=True)
    photoc = models.IntegerField(blank=True,null=True)
    tags = models.TextField(blank=True,null=True)

    def photoimg(self):
        """
            Esta función retorna el objeto imagen del modelo relación ContactFiles
   
        """
        try: 
            photoim = ContactFiles.objects.get(pk=self.photoc)
        except: 
            photoim = None
        return photoim

    def tages(self):
        """
            Esta función retorna el objeto imagen del modelo relación ContactFiles
   
        """
        if self.tags:
            tags = simplejson.loads(self.tags)
            listing = tags
        else:
            listing = None
        return listing

    def mytasks(self):
        #retorna un objeto con todas las tareas asignadas al contacto seleccionado
        t = Tasking.objects.filter(asigned_string='Contact',asignedto=self.pk)
        return t
    
    def __unicode__(self):
        return u'%s'%self.namec


    """
        las siguiente sfunciones extraen la información de MetaContact para el contacto seleccionado
    """
    def social(self):
        return self.metacontact_set.filter(asignetstring='redsocial')
    # Información de redes sociales

    def contacto(self):
        tels = self.metacontact_set.filter(asignetstring='contact',metastring__icontains='Tel')
        fones = []
        for t in tels:
            metavalue = t.metavalue.replace('|',' ')
            fones.append({'metastring':t.metastring,'metavalue':metavalue})
        return fones
    # Información de contacto...............

    def addresses(self):
        return self.metacontact_set.filter(asignetstring='direccion')
    # Direcciones

class MetaContact(models.Model):
    asignetstring = models.CharField(max_length=200)
    asignetto = models.IntegerField()
    metastring = models.CharField(max_length=200)
    metavalue = models.CharField(max_length=200)
    contact_meta = models.ForeignKey(Contact)




class EmailList(models.Model):
    contacto = models.ForeignKey(Contact)
    email = models.EmailField(unique=True)
    typeofemail = models.CharField(max_length=10,blank=True)


class Tag(models.Model):
    tagname = models.CharField(max_length=200,null=True,default='Untitle')
    def __unicode__(self):
        if self.tagname:
            return '%s' %(self.tagname[0].upper())
    
class Sepomex(models.Model):
    """
        Clase con la información geográfica del país: estados, demelaciones/municipios,Colonias, C.P.
    """
    codigo_postal = models.CharField(max_length=5)
    asentamiento = models.CharField(max_length=250)
    tipo_asentamiento = models.CharField(max_length=100)
    municipio = models.CharField(max_length=250)
    estado = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=250)
    descripcion_codigo_postal = models.CharField(max_length=5)
    clave_estado = models.CharField(max_length=2)
    clave_oficina = models.CharField(max_length=5)
    clave_tipo_asentamiento = models.CharField(max_length=5)
    clave_municipio = models.CharField(max_length=3)
    clave_asentamiento = models.CharField(max_length=2)
    zona = models.CharField(max_length=40)
    clave_ciudad = models.CharField(max_length=2)

class Note(models.Model):
    class Meta:
        ordering = ['date_create']
    
    text = models.TextField(default='untitle')
    sender = models.ForeignKey(User)
    receptor = models.ForeignKey(Contact)
    date_create = models.DateField(auto_now_add=True,default=datetime.now)


TYPES = (('option','option'),
         ('open','text'),
        )
class ExtraFields(models.Model):
    fieldname = models.CharField(u'Nombre del campo',max_length=200)
    typefield = models.CharField(u'Tipo de campo',max_length=200,choices=TYPES)
    ordering = models.IntegerField(default=1)
    
    def __unicode__(self):
        return '%s'%self.fieldname

class OptionFields(models.Model):
    fieldp = models.ForeignKey(ExtraFields)
    optiontxt = models.CharField(u'Opción',max_length=200)

    def __unicode__(self):
        return u'%s'%self.optiontxt

appentity/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
import simplejson
from appcontact.models import Contact


class EntityFile(models.Model):
    type_file = models.CharField(max_length=200,blank=True)
    entity_file = models.FileField(upload_to='entityFiles')
    '''
        status params 
         case 0 incomplete
         case 1 Complete
         case 2 Deleted
    
    '''

class Entity(models.Model):
    user = models.ForeignKey(User)
    nameac = models.CharField(u'Nombre Org.',max_length=200)
    emailacoount = models.CharField(u'Email',max_length=100,blank=True)
    url = models.CharField(u'Web',max_length=200,blank=True,null=True)
    extra = models.TextField(blank=True,null=True)
    photoa = models.IntegerField(blank=True,null=True)
    date_create = models.DateTimeField(auto_now_add=True)
    cpac = models.CharField(u'C.P.',max_length=20,null=True,blank=True)
    lonac = models.FloatField(default=0,blank=True,null=True)
    latac = models.FloatField(default=0,blank=True,null=True)
    estadoa = models.CharField(u'Estado',max_length=200)
    delomun = models.CharField(u'Del/Municipio',max_length=200)
    colonia = models.CharField(u'Colonia',max_length=200)
    tags = models.TextField(blank=True,null=True)

    def photoimg(self):
        try:
            photoim = EntityFile.objects.get(pk=self.photoa)
        except:
            photoim = None
        return photoim

    def mysocial(self):
        myc = self.metaentity_set.filter(asignetstring='redsocial')
        return myc

    def myaddrs(self):
        myc = self.metaentity_set.filter(asignetstring='direccion')
        return myc

    def tages(self):
        if self.tags:
            l = simplejson.loads(self.tags)
        else:
            l = None
        return l
    def __unicode__(self):
        return u'%s' % self.nameac


class EntitySocialInfo(models.Model):
    entity_id = models.ForeignKey(Entity)
    social_accounts = models.TextField()

class MetaEntity(models.Model):
    asignetstring = models.CharField(max_length=200)
    asignetto = models.IntegerField()
    metastring = models.CharField(max_length=200)
    metavalue = models.CharField(max_length=200)
    contact_meta = models.ForeignKey(Entity)




class As_Contact(models.Model):
    asociation = models.ForeignKey(Entity)
    contacto = models.ForeignKey(Contact)
    date_create = models.DateTimeField(auto_now=True)
 

appcontact/templates/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/chumbuket.css" %}" />
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/sitio.css" %}" />
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
       <script type="text/javascript" src="{% static "js/jquery-1.11.1.min.js"%}"></script>
        <script type="text/javascript" src=""></script>
        {% block kuppe %}{% endblock %}
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

appcontact/templates/base2.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
         <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="{% static "css/bootstrap2.min.css"%}">
        <link rel="stylesheet" href="{% static "css/bootstrap-theme2.min.css"%}">
       <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">       
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "bootstrap/css/bootstrap.css" %}" />
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/chumbuket.css" %}" />
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/contacts.css" %}" />
        <script type="text/javascript" src="{% static "js/jquery-1.11.1.min.js"%}"></script>
        {% block kuppe %}{% endblock %}
        <script>
            modal=false;
        </script>
         <!-- Optional theme -->
        {% block css %}{% endblock %}
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <script type="text/javascript" src="{% static "js/bootstrap.min.js"%}"></script>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/sitio.css" %}" />
        <script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
        <script type="text/javascript" src="{% static "js/combobox.js"%}"></script>
        {% block js %}{% endblock %}
        <script type="text/javascript">

        htmlpopover = '<div><a href="/logout">Cerrar sesión</a></div><div><a href="/edtcontact/{{user.contact_set.all.0.pk}}">Editar mi cuenta</a></div>';

        $(document).ready(function(){
                {% block document_ready %}
                {% endblock %}
                    var popOverSettings = { //Save the setting for later use as well
                        placement: 'left',
                        container: 'body',
                        html: true,
                        content:htmlpopover

                        }
                $('.fa-cog').popover(popOverSettings);
            });

    </script>
    </head>
    <body>
<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Agregar una tarea</h4>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

        <div class="table_n">
            <div class="table_r">
                <div class="table_c lefty">{% include "menu_left.html" %}</div>
                <div class="table_c">
                    <div id="top_right">
                        {% include "top_right.html"%}
                    </div>
                    <div>
                        <div id="inicio_box">
                        {% block content %}{% endblock %} 
                        </div>           
                    </div>
                </div>
            </div>
        </div>
                       
       
        
        </div>   
    </body>

        {% block contentjs %}
        {% endblock %}  
 
</html>

appcontact/templates/header.html
<div id="header_box">
    <div id="logo" class="inline_blocke"><a href="/" class="inline_blocke">D4</a></div>
    <ul id="menu_list" class="inline_blocke">
        <li class="inline_blocke"><a href="/contacto">Nuevo contacto</a></li>
        <li class="inline_blocke"><a href="/entity">Nueva Organización</a></li>
        <li class="inline_blocke"><a href="/logout">Salir</a></li>
        <li class="inline_blocke"></li>
     </ul>
</div>

appcontact/templates/menu_left.html
<div id="logo_box">
    <span id="logo" class="inline_blocke"><img src="/static/images/logohome.jpg" /></span>
<!--    <a href="/" class="inline_blocke"><img src="/static/images/btn_home.jpg" /></a>
    <div class="inline_blocke lnk_ms" style="text-align:right;">
        <a href="#btn" class="inline_blocke red_round">2</a>
    </div>
-->
</div>

<div id="user_info_box">
    <div class="inline_blocke" id="photo_home" style="margin:5% 0px;background:url(/static/{{user.contact_set.all.0.photoimg.contact_file.url}}) no-repeat;background-size:cover;">
    </div>
    <div class="inline_blocke name_box">
        <h4 class="salute">Bienvenido</h4>
        <div class="myname">{{user.contact_set.all.0.namec}}</div>
        <div class="myname">{{user.contact_set.all.0.lastname}}</div>
    </div>
</div>
<ul id="left_menu">
    <li><a href="/" class="inline_blocke"><span class="fa fa-home iconic"></span><span>Bienvenido</span></a></li>
    <li class="blind"><a href="#" class="inline_blocke"><img src="/static/images/l2.png" />Actividad Reciente</a></li>
    <li>
        <a href="/mycontacts" class="inline_blocke"><span class="fa fa-user iconic"></span>Contacto</a>
    </li>
    <li>
        <a href="/myentities"><span class="fa fa-users iconic"></span>Organización</a>
    </li>
    <li><a href="/mytasks" ><span class="fa fa-check iconic"></span>Tareas</a></li>
     <li class="blind"><a href="#"><img src="/static/images/l5.png" />Buscador > </a></li>
</ul>
<div id="reciente" style="display:none;">
    <div class="hdt" style="padding-bottom:5px;">&nbsp;&nbsp;VISTO RECIENTE&nbsp;&nbsp;</div>
    <ul>
        <li>
            <img src="/static/images/nophoto.jpg" height="33px">
            <div class="inline_blocke">
                <div class="name_left">This is his name</div>
                <div class="text_left">This is his charge</div>
            </div>
        </li>
         <li>
            <img src="/static/images/nophoto.jpg" height="33px">
            <div class="inline_blocke">
                <div class="name_left">This is his name</div>
                <div class="text_left">This is his charge</div>
            </div>
        </li>
       <li>
            <img src="/static/images/nophoto.jpg" height="33px">
            <div class="inline_blocke">
                <div class="name_left">This is his name</div>
                <div class="text_left">This is his charge</div>
            </div>
        </li>
    </ul>
 </div> 

appcontact/templates/mycontacts.html
{% extends 'base2.html'%}
{% load tager %}
{% load staticfiles %}


{% block kuppe %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/contacts.css" %}" />
    <script type="text/javascript" src="{% static "js/validations.js" %}"></script>
    <script type="text/javascript" src="{% static "js/contacts.js" %}"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script type="text/javascript" src="{% static "js/geolocalizations.js" %}"></script>
 

    <script type="text/javascript">
        var locations = [];
        {% for c in contacts %}
            if('{{c.lat}}'.length>4 && '{{c.lon}}'.length>4){
                place  = new google.maps.LatLng({{c.lat}},{{c.lon}});
                data = {
                    'id':'{{c.pk}}',
                    'name':'{{c.namec}}',
                    'location':place,
                    'locations':'{{c.addresses.0.metavalue}}<br/> {{c.colonia}} {{c.delomun}} {{c.estado}}',
                    'icon':'contact.png',
                    'photo':'{% if c.photoc %}/static/{{c.photoimg.contact_file.url}}{% else%}/static/images/nophoto.png{%endif%}'
                }
                locations.push(data);
            }
       {% endfor%}
        var the_place = null;
        var map;

function chowmap(){
        if(map){
            nothingtodo=true;
        }
        else{
            var geocoder = new google.maps.Geocoder();
            geocoder.geocode({'address':'Mexico'},function(results,status){
            if(status==google.maps.GeocoderStatus.OK){
                the_place = new google.maps.LatLng(results[0].geometry.location.k, results[0].geometry.location.B);
                draw_map();
            }    
            else{
                alert('some problem with maps');    
            }
            });
        }
   
}

$(document).ready(function(){
    $('[href=#map_canvas]').click(chowmap);    

        $('.tagger').click(tagger);

        $('.removetagg').click(removetag);


        if(locations.length<1){
            $('#map_link').html('');
        
        }
 

});
</script>
{% endblock %}


{% block content %}
<div class="table_n">
    
    <div class="table_r white_box">
            <div id="layout_box" class="table_c">
                <h2 class="title-2">Mis Contactos</h2>
                {% include 'forms/search_form.html'%}
                <!-- Nav tabs -->
                 {% if contacts%}
                    <ul class="pagination">
                        <li>
                            {% if contacts.has_previous %}
                                <a href="?page={{ contacts.previous_page_number }}">Anterior</a>
                            {% endif %}
                        </li>
                        {% for np in contacts.paginator.page_range %}
                        <li>
                             <span class="current">
                                   <a href="?page={{np}}">{{np}}</a>
                            </span>
                        </li>
                        {% endfor %}
                        <li>
                             {% if contacts.has_next %}
                                <a href="?page={{ contacts.next_page_number }}">Siguiente</a>
                            {% endif %}

                       </li>
                    </ul>
                {% endif%}

               <ul class="nav nav-tabs" role="tablist">
                    <li class="active"><a href="#list_results" role="tab" data-toggle="tab">Listado</a></li>
                    <li id="map_link"><a href="#map_canvas"  role="tab" data-toggle="tab">Mapa</a></li>
                </ul>
                <br/>
                <div class="tab-content">
                    <ul id="list_results" class="tab-pane fade in active">
                        {% for c in contacts %}
                        <li>
                            <div class="inline_blocke boxy">&nbsp;</div>
                            {% if c.photoc %}
                            <div class="inline_blocke myminiphoto" style="background-image:url(/static/{{c.photoimg.contact_file.url}});">
                                <a href="/detailcontact/{{c.pk}}/" class="inline_blocke" style="width:100%;height:100%;">&nbsp;</a>
                            </div>
                            {% else %}
                             <div class="inline_blocke myminiphoto" style="background-image:url(/static/images/nophoto.png);">
                            </div>
                            {% endif %}
                            <div class="inline_blocke" style="width:80%;">
                                <a href="/detailcontact/{{c.pk}}/" class="t4">
                                <div>{{c.namec}} {{c.lastname}}</div>
                                {% for c in c.contacto %}
                                <div class="t5">{{c.metastring}} {{c.metavalue}}</div>
                                {% endfor %}
                                {% for m in c.emaillist_set.all %}
                                <div class="t5">{{m.email}}</div>
                                {% endfor %}
                                {% for adr in c.addresses %}
                                <div class="t5">{{adr.metavalue}}</div>
                                {% endfor %}
                                <div class="t5">{{c.colonia}} {{c.delomun}} {{c.estado}}</div>
                                </a>
                                 {% for asoc in c.as_contact_set.all %}
                                <div class="t4"><a href="/detailentity/{{asoc.asociation.pk}}">{{asoc.asociation.nameac}}</a></div>
                                {% endfor%}
                                <div class="tag_block">
                                  {% for a in c.tages %}
                                        <span class="inline_blocke tags">{{a}}</span>
                                    {% endfor%}
                                </div>
                            </div>
                       </li>
                        {% endfor %}
                    </ul>
                    <div id="map_canvas"  class="tab-pane fade" style="width:100%;height:400px;border-radius:20px;"></div>
                </div>
            </div>
            <div class="tablec">{% include 'pices/tags.html' %}</div>

    </div>
</div>



{% endblock %}

appcontact/templates/myresults.html
{% extends 'base2.html'%}

{% load staticfiles %}


{% block kuppe %}
    <script type="text/javascript" src="{% static "js/validations.js" %}"></script>
    <script type="text/javascript" src="{% static "js/forms.js" %}"></script>
    <script type="text/javascript" src="{% static "js/contacts.js" %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script type="text/javascript" src="{% static "js/geolocalizations.js" %}"></script>
    <script type="text/javascript">
        var locations = [];
        {% for c in response %}
            if('{{c.lat}}'!='0.0' && '{{c.lon}}'!='0.0'){
                place  = new google.maps.LatLng({{c.lat}},{{c.lon}});
                data = {
                    'name':'{{c.name}}',
                    'location':place,
                    'icon':'{{c.icon}}'
                }
                locations.push(data);
            }

        {% endfor%}
        var the_place = null;
        var map;


function chowmap(){
        if(map){
            nothingtodo=true;
        }
        else{
            var geocoder = new google.maps.Geocoder();
            geocoder.geocode({'address':'Mexico'},function(results,status){
            if(status==google.maps.GeocoderStatus.OK){
                the_place = new google.maps.LatLng(results[0].geometry.location.k, results[0].geometry.location.B);
                draw_map();
            }    
            else{
                alert('some problem with maps');    
            }
            });
        }
   
}


    $(document).ready(function(){
        $('[href=#map_canvas]').click(chowmap);    

        $('.tagger').click(tagger);

        $('.removetagg').click(removetag);
});
</script>
{% endblock %}
{% block content %}
<div class="table_n">
    <div class="table_r white_box">
            <div id="layout_box" class="table_c">
               <h2 class="title-2">Mis Resultados</h2>
               {% include 'forms/search_form.html'%}
                  {% if response%}
                    <ul class="pagination">
                        <li>
                            {% if response.has_previous %}
                                <a href="?page={{ response.previous_page_number }}">previous</a>
                            {% endif %}
                        </li>
                         {% for np in response.paginator.page_range %}
                        <li>
                             <span class="current">
                                   <a href="?page={{np}}">{{np}}</a>
                            </span>
                        </li>
                        {% endfor %}
                       <li>
                             {% if response.has_next %}
                                <a href="?page={{ response.next_page_number }}">next</a>
                            {% endif %}

                       </li>
                    </ul>
                {% endif%}

              <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li class="active"><a href="#list_results" role="tab" data-toggle="tab">Listado</a></li>
                    <li><a href="#map_canvas" role="tab" data-toggle="tab">Mapa</a></li>
                </ul>
                <br/>
                <div class="tab-content">
                    <ul id="list_results" class="tab-pane fade in active">
                        {% for c in response  %}
                        <li>
                            <a href="{{c.link}}" class="t4">
                            <div class="inline_blocke boxy">&nbsp;</div>
                            {% if c.photoimg.entity_file.url %}
                            <div class="inline_blocke myminiphoto" 
                            style="background-image:url('/static/{{c.photoimg.entity_file.url}}');">&nbsp;</div>
                             {% elif c.photoimg.contact_file.url %}
                            <div class="inline_blocke myminiphoto" 
                            style="background-image:url('/static/{{c.photoimg.contact_file.url}}');">&nbsp;</div>
                            {% else %}
                            <div class="inline_blocke myminiphoto" style="background-image:url(/static/images/nophoto.png);"/></div>
                            {% endif %}
                            <div class="inline_blocke">
                                <p class="t5">{{c.type}}</p>
                                
                                <p>{{c.name}}</p>
                                {% if c.type in 'Contacto'%}
                                    {% for m in c.me.emaillist_set.all %}
                                    <div class="t5">{{m.email}}</div>
                                    {% endfor %}
                                    {% for adr in c.me.addresses %}
                                    <div class="t5">{{adr.metavalue}}</div>
                                    {% endfor %}
                                    </a>
                                    {% for asoc in c.me.as_contact_set.all %}
                                    <div class="t4"><a href="/detailentity/{{asoc.asociation.pk}}">{{asoc.asociation.nameac}}</a></div>
                                    {% endfor%}
                               {% else %}
                                    {% for adr in c.me.myaddrs %}
                                    <div class="t5">{{adr.metavalue}}</div>
                                    {% endfor %}
                                    </a>

                                {% endif %}


                                <div class="tag_block">
                                  {% for a in c.me.tages %}
                                        <span class="inline_blocke tags">{{a}}</span>
                                    {% endfor%}
                                </div>
                        </li>
                        {% endfor %}
                    </ul>
                    <div id="map_canvas" class="tab-pane fade"  style="width:100%;height:400px;border-radius:20px;"></div>
                </div>
                </div>
            {% include "pices/tags.html"%}
    </div>
</div>
{% endblock %}